server:
  port: 8887
  servlet:
    session:
      timeout: 15552000
spring:
  datasource:
    driver-class-name: '@db.driver@'
    password: '@db.password@'
    url: jdbc:mysql://127.0.0.1:3306/community?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: '@db.user@'
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: life.majiang.community.mapper
logging:
  file: logs/community.log
  file.max-history: 15
  file.max-size: 100MB
  level:
    root: info
ucloud:
  ufile:
    bucketName: mawen
    bucketType: private
    downloadDomain: mawen.cn-bj.ufileos.com
    expiresDuration: 315360000
    privateKey: 18977163-f21e-4deb-a2e3-9bfa0b888ba5
    publicKey: TOKEN_f465454a-f3ab-4c9b-91a5-c7babf59cc38
    uploadDomain: mawen.cn-bj.ufileos.com
gitee:
  client:
    id: e542c33bb680ea612ce21b8efb397274eae34833553bc80bc9ff881425d1b883
    secret: 5181b24983dd562b8089f59d212f391e315d0649ecec3db13ef07830a61a7aa9
  redirect:
    uri: http://localhost:8887/callback/gitee
github:
  client:
    id: 7f316909bf70d1eaa2b2
    secret: 3c6f5cd2fceb99e3c8a338f53bb5e29ed156b2ef
  redirect:
    uri: http://localhost:8887/callback/github
